/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: ['./src/**/*.{js,jsx,ts,tsx}'],
  theme: {
    extend: {
      colors: {
        'primary-container': '#00f1fe',
        'tertiary': '#6fb5ff',
        'surface-dim': '#080f18',
        'outline-variant': '#424853',
        'secondary-container': '#27496c',
        'on-background': '#e8eefc',
        'surface-container-lowest': '#000000',
        'surface-container-low': '#0c141e',
        'on-surface': '#e8eefc',
        'background': '#080f18',
        'surface-container': '#121a25',
        'error-container': '#9f0519',
        'surface': '#080f18',
        'on-secondary': '#28496d',
        'surface-variant': '#1d2634',
        'on-surface-variant': '#a5abb8',
        'primary-dim': '#00e2ee',
        'error': '#ff716c',
        'on-error-container': '#ffa8a3',
        'tertiary-container': '#4da8fe',
        'on-error': '#490006',
        'tertiary-fixed': '#6fb5ff',
        'secondary': '#b3d4ff',
        'primary': '#99f7ff',
        'surface-container-high': '#17202c',
        'on-primary': '#005f64',
        'surface-bright': '#222d3b',
        'primary-fixed-dim': '#00e2ee',
        'on-primary-container': '#00555a',
        'tertiary-fixed-dim': '#4da8fe',
        'outline': '#6f7682',
        'surface-container-highest': '#1d2634',
        'error-dim': '#d7383b',
      },
      fontFamily: {
        headline: ['Space Grotesk', 'sans-serif'],
        body: ['Manrope', 'sans-serif'],
        label: ['Inter', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
    },
  },
  plugins: [],
};
